### ISSUE TITLE
Error with cv2.mean in bgsegm.py

### ISSUE THREAD

**Issue by ghost** [peterzajac39/football-processing-opencv#2]
Hi, I have encountered an error when test a new video on bgsegm.py.
This error is as below:
Traceback (most recent call last):
  File "bgsegm.py", line 130, in <module>
    dict = classifycontours(contours)
  File "bgsegm.py", line 31, in classifycontours
    meanColor = cv2.mean(crop_img, mask=mask)
cv2.error: /io/opencv/modules/core/src/matrix.cpp:4845: error: (-215) A.size == arrays[i0]->size in function init

I use opencv 3.4.0.12
Could you help me to fix that problem :D

**Comment by HHIR** [comment]
@ngthanhtin  I have the same error... I want to ask you did you solve your problem?
